### ISSUE TITLE
Evohome multiple locations

### ISSUE THREAD

**Issue by vertol-cz** [watchforstock/evohome-client#106]
Hi, 
I need to integrate 4 evohome locations into HA. Is there any chance to do it? I am aware that evohome component docs says that multiple locations at one time are not suported. Is there any plan for component improvement for multiple locations? If there is any serious issue with multiple locations at one time, is there any option how to switch between locations? 
Your help is very appreciated !

**Comment by zxdavb** [comment]
@vertol-cz The latest versions of HA use an **async** version of this library, which is a [different repo](https://github.com/zxdavb/evohome-async).

The async version is _exactly_ the same as this version (other than using [aiohttp](https://pypi.org/project/aiohttp/) instead of [requests](https://pypi.org/project/requests2/)), and both can support multiple locations with minimal workaround.

Your question is best asked [over at HA](https://community.home-assistant.io/t/official-honeywell-evohome-round-thermostat-integration-eu-only/59733), in any case.

Nonetheless, I wrote the HA integration for evohome, and I can say this:
 - multiple locations are supported, but only _one at a time_ (there will be limitations on higher-precision temps)
 - there are no plans by _me_ for concurrent support of multiple locations

**Comment by vertol-cz** [comment]
Thank you for your  explanation David, I will try to deal with it ! You support is very appreciated!

**Comment by watchforstock** [comment]
@zxdavb  Thanks for your answer!
