### ISSUE TITLE
Accessing the "custom" schedule

### ISSUE THREAD

**Issue by cooperised** [watchforstock/evohome-client#121]
Engaging "custom" mode causes a subset of the heating zones to follow the (singleton) "custom" schedule instead of their own.

Is there any way to access or modify the custom schedule, or the configuration information about which zones it applies to?  If not, has anyone documented the API for any of this?

**Comment by watchforstock** [comment]
The rule of thumb is if the functionality is in the mobile app then it's plausible to add support for that. I've just had a quick look and can't see anywhere in the app where I can view or change the custom schedule or zones. If you do find it in the app then we'd have a route forward, otherwise it's unlikely to be exposed

**Comment by cooperised** [comment]
Thanks for the quick response.  Didn't even think to check the app!  I agree, I can't see that functionality either so it sounds like it's a non-starter.  I guess it could be buried somewhere (the app interface is not great!) but I suspect not.

Thanks again.
