### ISSUE TITLE
Data no longer automatically refreshed when calling EvohomeClient.temperatures()

### ISSUE THREAD

**Issue by tmacecode** [watchforstock/evohome-client#89]
Sorry this may be a deliberate change and not a bug, but in the previous release (0.2.8) a call to EvohomeClient.temperatures() would result in the status data being refreshed due to line 73 of controlsystem.py

status = self.location.status()

But in the latest version (0.3.1) that status call doesn't exist.

Is the intention now that the user has to manually request that the status data is refreshed?

**Comment by watchforstock** [comment]
Thanks for the report - I don't believe this was intentional (or at least I don't recall a discussion about it). It looks like in this commit (https://github.com/watchforstock/evohome-client/commit/f57fd55020a7bdb6a409a60f6b91025ea82dbb9b#diff-91be0e17c72f324a8437009c3c5c42bb) @zxdavb commented it out and presumably it was then subsequently removed. David, any view as to whether there was a reason behind this change?

**Comment by zxdavb** [comment]
@watchforstock I am sorry!

I think I was testing an idea, and then deleted the line, rather than remove the `#`.

**Comment by zxdavb** [comment]
TBH, the amount of refactoring that went on, we're lucky the bloody thing hasn't exploded!

**Comment by watchforstock** [comment]
@zxdavb Indeed! Thanks for the PR. @tmacecode This should now be fixed in master, but isn't yet in a released version.

**Comment by tmacecode** [comment]
That is great, thank you. 

 

How often do you cut a new release?

**Comment by watchforstock** [comment]
@tmacecode v0.3.2 is now available on pypi with this change in it...
